echo "First number is $num1" 
echo "Second number is $num2" 
echo "Addition of both the numbers is : $((num1 + num2)), added by Anill"
echo "This script will now be pulled from webhook" 
echo " New changes added" 
echo "absahch" 
echo "Added by Anil"
